package main

import (
	"flag"
	"fmt"
	"io"
)

// commandFunc is the signature for every subcommand. It receives the args
// after the subcommand name (so for `dcs-sms exec --file foo.lua`,
// argsAfterCmd would be ["--file", "foo.lua"]). It returns an OS exit code.
type commandFunc func(argsAfterCmd []string, stdout, stderr io.Writer) int

// cmdInfo carries everything the dispatcher and the doc generator need
// about one subcommand. Flags and Synopsis are optional; when both are
// non-empty, the command is included in the autogenerated reference docs
// at docs/cli/. When Flags is nil OR Synopsis == "" the command is treated
// as hidden by the doc generator.
type cmdInfo struct {
	Run      commandFunc
	Flags    func() *flag.FlagSet
	Synopsis string
	Examples []string // TODO(#49 doc gen): consumed by `dcs-sms doc` once Task 10 lands

	// SubCommands documents verbs that dispatch on a further positional token
	// (e.g. `me unit payload set`, `... set-fuze`). The umbrella command's Run
	// routes to them itself; the doc generator renders one flags table per
	// sub-command so each sub-verb's flags are documented. A command with
	// SubCommands set but Flags == nil is still included in the reference.
	SubCommands []subCommand
}

// subCommand is one documented sub-verb of an umbrella command.
type subCommand struct {
	Name     string
	Synopsis string
	Flags    func() *flag.FlagSet
}

// commands maps subcommand names to their metadata. Subcommands register
// themselves here in init() blocks across cmd/dcs-sms/*.go.
var commands = map[string]cmdInfo{}

// registerInfo registers a command with full metadata (the new canonical API).
func registerInfo(name string, info cmdInfo) {
	if info.Run == nil {
		panic("registerInfo: Run is required for " + name)
	}
	if _, exists := commands[name]; exists {
		panic("duplicate command registration: " + name)
	}
	commands[name] = info
}

// register is a backward-compatible wrapper for the old (name, fn) API.
// Prefer registerInfo for new code; this exists so the migration to the
// doc-aware registry can land incrementally per namespace.
func register(name string, fn commandFunc) {
	registerInfo(name, cmdInfo{Run: fn})
}

// flagsOnly adapts a flags-builder of the form `func() (*flag.FlagSet, *Opts)`
// to the `func() *flag.FlagSet` shape that cmdInfo.Flags expects. The doc
// generator only needs the FlagSet; the opts pointer is for the run handler.
//
// Use as: registerInfo("foo", cmdInfo{ ..., Flags: flagsOnly(fooFlags), ... })
func flagsOnly[T any](b func() (*flag.FlagSet, T)) func() *flag.FlagSet {
	return func() *flag.FlagSet {
		fs, _ := b()
		return fs
	}
}

// dispatch routes args[0] (subcommand name) to its handler. With no args,
// behavior depends on `interactive`: a real terminal gets the menu; a
// piped/scripted stdin gets today's "print usage + exit 2" behavior.
func dispatch(args []string, stdin io.Reader, stdout, stderr io.Writer, interactive bool) int {
	if len(args) == 0 {
		if interactive {
			return runInteractiveMenu(stdin, stdout, stderr)
		}
		printUsage(stderr)
		return 2
	}
	switch args[0] {
	case "--version", "-v", "version":
		fmt.Fprintln(stdout, version)
		return 0
	case "--help", "-h", "help":
		printUsage(stdout)
		return 0
	}
	cmd, ok := commands[args[0]]
	if !ok {
		fmt.Fprintf(stderr, "dcs-sms: unknown command %q\n", args[0])
		printUsage(stderr)
		return 2
	}
	return cmd.Run(args[1:], stdout, stderr)
}

func printUsage(w io.Writer) {
	fmt.Fprintln(w, "dcs-sms — Digital Combat Simulator scripting bridge")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Usage: dcs-sms <command> [flags]")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Commands:")
	fmt.Fprintln(w, "  exec          execute a Lua snippet (use --target mission|gui|auto, default auto)")
	fmt.Fprintln(w, "  me            Mission Editor commands (run `dcs-sms me --help` for the verb list)")
	fmt.Fprintln(w, "  status        report whether the hook is alive and a mission is loaded")
	fmt.Fprintln(w, "  screenshot    capture the DCS window to a PNG (Windows only)")
	fmt.Fprintln(w, "  setup         update dcs-sms.exe, then install the ME mod and the hook in one shot")
	fmt.Fprintln(w, "  dev-reload    contributor: build the .exe, reinstall the ME mod, hot-reload it in one shot")
	fmt.Fprintln(w, "  tail-log      read recent lines from dcs.log")
	fmt.Fprintln(w, "  teardown      remove the ME mod and the hook in one shot")
	fmt.Fprintln(w, "  install-hook  install/update the Lua hook + patch MissionScripting.lua to allow it")
	fmt.Fprintln(w, "  install-me-mod   install/update the Mission Editor mod into <DCS install>/MissionEditor/")
	fmt.Fprintln(w, "  reload-me-mod    hot-reload the installed ME mod via the gui bridge (no DCS restart)")
	fmt.Fprintln(w, "  uninstall-hook   remove the Lua hook + revert the MissionScripting.lua patch")
	fmt.Fprintln(w, "  uninstall-me-mod remove the Mission Editor mod (revert MissionEditor.lua, delete modules)")
	fmt.Fprintln(w, "  install-ai-skill   write a 'dcs-sms' skill into ~/.claude / ~/.agents / ~/.gemini")
	fmt.Fprintln(w, "  uninstall-ai-skill remove the 'dcs-sms' skill from one or all AI agent config dirs")
	fmt.Fprintln(w, "  gen-units     regenerate framework/constants/{units,statics}.lua from dcs-lua-datamine")
	fmt.Fprintln(w, "  update        download the latest dcs-sms.exe from GitHub and replace this binary")
	fmt.Fprintln(w, "  doc           regenerate docs/cli/ — per-command markdown reference + index")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Run `dcs-sms <command> --help` for command-specific flags.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Tip: double-click dcs-sms.exe (or run with no arguments from a real terminal)")
	fmt.Fprintln(w, "for an interactive install/uninstall/update menu.")
}
