package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func init() {
	registerInfo("doc", cmdInfo{
		Run:      docCmd,
		Flags:    flagsOnly(docFlags),
		Synopsis: "regenerate docs/cli/ — per-command markdown reference + index",
	})
}

type docOpts struct {
	OutDir string
}

func docFlags() (*flag.FlagSet, *docOpts) {
	opts := &docOpts{}
	fs := flag.NewFlagSet("doc", flag.ContinueOnError)
	fs.StringVar(&opts.OutDir, "out", "docs/cli", "output directory for generated markdown")
	return fs, opts
}

func docCmd(args []string, stdout, stderr io.Writer) int {
	fs, opts := docFlags()
	fs.SetOutput(stderr)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		fmt.Fprintln(stderr, "dcs-sms doc:", err)
		return 3
	}
	pages := collectPages()
	for _, p := range pages {
		path := filepath.Join(opts.OutDir, p.Slug+".md")
		if err := os.WriteFile(path, []byte(renderPage(p)), 0o644); err != nil {
			fmt.Fprintln(stderr, "dcs-sms doc:", err)
			return 3
		}
	}
	indexPath := filepath.Join(opts.OutDir, "README.md")
	if err := os.WriteFile(indexPath, []byte(renderIndex(pages)), 0o644); err != nil {
		fmt.Fprintln(stderr, "dcs-sms doc:", err)
		return 3
	}
	fmt.Fprintf(stdout, "wrote %d command pages + index to %s\n", len(pages), opts.OutDir)
	return 0
}

// docPage is one rendered command's data, ready for templating.
type docPage struct {
	Name     string // "exec" or "me zone create"
	Slug     string // "exec" or "me-zone-create"
	Group    string // "Top-level", "me zone", etc.
	Synopsis string
	Examples []string
	Flags    []docFlag
	SubVerbs []docSubVerb // sub-commands (e.g. payload set / set-fuze), each with its own flags
}

type docFlag struct {
	Name    string
	Type    string
	Default string
	Usage   string
}

// docSubVerb is one sub-command's rendered data (name + synopsis + flags).
type docSubVerb struct {
	Name     string
	Synopsis string
	Flags    []docFlag
}

func collectPages() []docPage {
	var pages []docPage

	// Top-level commands
	topNames := make([]string, 0, len(commands))
	for n := range commands {
		topNames = append(topNames, n)
	}
	sort.Strings(topNames)
	for _, name := range topNames {
		info := commands[name]
		if info.Synopsis == "" || (info.Flags == nil && len(info.SubCommands) == 0) {
			continue // hidden
		}
		// Skip the special "me" dispatch entry — its sub-commands have their own pages.
		if name == "me" {
			continue
		}
		pages = append(pages, buildPage(name, "Top-level", info))
	}

	// me <noun> <verb>
	nouns := make([]string, 0, len(meCommands))
	for n := range meCommands {
		nouns = append(nouns, n)
	}
	sort.Strings(nouns)
	for _, noun := range nouns {
		verbs := make([]string, 0, len(meCommands[noun]))
		for v := range meCommands[noun] {
			verbs = append(verbs, v)
		}
		sort.Strings(verbs)
		for _, verb := range verbs {
			info := meCommands[noun][verb]
			if info.Synopsis == "" || (info.Flags == nil && len(info.SubCommands) == 0) {
				continue
			}
			pages = append(pages, buildPage("me "+noun+" "+verb, "me "+noun, info))
		}
	}
	return pages
}

func buildPage(name, group string, info cmdInfo) docPage {
	page := docPage{
		Name:     name,
		Slug:     strings.ReplaceAll(name, " ", "-"),
		Group:    group,
		Synopsis: info.Synopsis,
		Examples: info.Examples,
	}
	if info.Flags != nil {
		page.Flags = collectFlags(info.Flags())
	}
	for _, sc := range info.SubCommands {
		sv := docSubVerb{Name: sc.Name, Synopsis: sc.Synopsis}
		if sc.Flags != nil {
			sv.Flags = collectFlags(sc.Flags())
		}
		page.SubVerbs = append(page.SubVerbs, sv)
	}
	return page
}

// collectFlags flattens a FlagSet into the doc model.
func collectFlags(fs *flag.FlagSet) []docFlag {
	var out []docFlag
	fs.VisitAll(func(f *flag.Flag) {
		out = append(out, docFlag{
			Name:    f.Name,
			Type:    flagType(f),
			Default: f.DefValue,
			Usage:   f.Usage,
		})
	})
	return out
}

// flagType returns a short type label for a flag, derived from the
// underlying flag.Value implementation. Falls back to "value" for custom
// flag.Value types we don't recognize.
func flagType(f *flag.Flag) string {
	switch fmt.Sprintf("%T", f.Value) {
	case "*flag.stringValue":
		return "string"
	case "*flag.intValue":
		return "int"
	case "*flag.int64Value":
		return "int"
	case "*flag.uintValue", "*flag.uint64Value":
		return "uint"
	case "*flag.float64Value":
		return "float"
	case "*flag.boolValue":
		return "bool"
	case "*flag.durationValue":
		return "duration"
	case "*main.stringSliceFlag":
		return "string (repeatable)"
	}
	return "value"
}

func renderIndex(pages []docPage) string {
	var b strings.Builder
	b.WriteString("# dcs-sms CLI reference\n\n")
	b.WriteString("Autogenerated by `dcs-sms doc`. Do not edit by hand — run `dcs-sms doc -out docs/cli` to regenerate.\n\n")
	b.WriteString("Every command on the dcs-sms CLI, grouped by namespace.\n\n")

	// Group pages by Group field, preserving "Top-level" first.
	groups := []string{"Top-level"}
	byGroup := map[string][]docPage{}
	for _, p := range pages {
		if _, seen := byGroup[p.Group]; !seen && p.Group != "Top-level" {
			groups = append(groups, p.Group)
		}
		byGroup[p.Group] = append(byGroup[p.Group], p)
	}
	// Sort the me-* groups alphabetically (groups[0] is always "Top-level").
	if len(groups) > 1 {
		rest := groups[1:]
		sort.Strings(rest)
		groups = append([]string{"Top-level"}, rest...)
	}

	for _, g := range groups {
		gp := byGroup[g]
		if len(gp) == 0 {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n", g)
		b.WriteString("| Command | Description |\n")
		b.WriteString("|---|---|\n")
		for _, p := range gp {
			fmt.Fprintf(&b, "| [`%s`](%s.md) | %s |\n", p.Name, p.Slug, escapePipe(p.Synopsis))
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderPage(p docPage) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# `dcs-sms %s`\n\n", p.Name)
	b.WriteString("[← CLI reference index](README.md)\n\n")
	fmt.Fprintf(&b, "%s\n\n", p.Synopsis)
	b.WriteString("## Usage\n\n")
	if len(p.SubVerbs) > 0 {
		names := make([]string, len(p.SubVerbs))
		for i, sv := range p.SubVerbs {
			names[i] = sv.Name
		}
		fmt.Fprintf(&b, "```\ndcs-sms %s <%s> [flags]\n```\n\n", p.Name, strings.Join(names, "|"))
	} else {
		fmt.Fprintf(&b, "```\ndcs-sms %s [flags]\n```\n\n", p.Name)
	}

	if len(p.Flags) > 0 {
		b.WriteString("## Flags\n\n")
		writeFlagsTable(&b, p.Flags)
	}

	for _, sv := range p.SubVerbs {
		fmt.Fprintf(&b, "## `%s`\n\n", sv.Name)
		if sv.Synopsis != "" {
			fmt.Fprintf(&b, "%s\n\n", sv.Synopsis)
		}
		if len(sv.Flags) > 0 {
			writeFlagsTable(&b, sv.Flags)
		}
	}

	if len(p.Examples) > 0 {
		b.WriteString("## Examples\n\n")
		for _, ex := range p.Examples {
			fmt.Fprintf(&b, "```\n%s\n```\n\n", ex)
		}
	}

	b.WriteString("---\n\n")
	b.WriteString("[← CLI reference index](README.md)\n")
	return b.String()
}

// writeFlagsTable renders a markdown flags table for a flag set.
func writeFlagsTable(b *strings.Builder, flags []docFlag) {
	b.WriteString("| Name | Type | Default | Description |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, f := range flags {
		def := f.Default
		if def == "" {
			def = `""`
		}
		fmt.Fprintf(b, "| `--%s` | %s | `%s` | %s |\n",
			f.Name, f.Type, def, escapePipe(f.Usage))
	}
	b.WriteString("\n")
}

// escapePipe replaces literal `|` with `\|` so it doesn't break markdown table cells.
func escapePipe(s string) string {
	return strings.ReplaceAll(s, "|", `\|`)
}
