package main

import (
	"flag"
	"fmt"
	"io"
	"time"
)

type meDrawingGetOpts struct {
	Name		string
	Timeout		time.Duration
	Pretty		bool
	SavedGames	string
}

func meDrawingGetFlags() (*flag.FlagSet, *meDrawingGetOpts) {
	opts := &meDrawingGetOpts{}
	fs := flag.NewFlagSet("me drawing get", flag.ContinueOnError)
	fs.StringVar(&opts.Name, "name", "", "drawing name")
	fs.DurationVar(&opts.Timeout, "timeout", 30*time.Second, "wall-clock timeout")
	fs.BoolVar(&opts.Pretty, "pretty", false, "indent JSON output")
	fs.StringVar(&opts.SavedGames, "saved-games", "", "override Saved Games path")
	return fs, opts
}

func init() {
	registerMeInfo("drawing", "get", cmdInfo{
		Run:		meDrawingGetCmd,
		Flags:		flagsOnly(meDrawingGetFlags),
		Synopsis:	"return full data for a drawing by name",
	})
}

// meDrawingGetCmd implements `dcs-sms me drawing get --name <X>`.
//
// Returns the full drawing structure (primitiveType, polygonMode,
// shape-specific fields, color, layer, etc.) plus translated --north /
// --east. mapId and mapData are stripped — mapId is a render-side
// handle and mapData is regenerated by loadFromMission from the
// on-disk fields, so neither belongs in the writable surface.
func meDrawingGetCmd(args []string, stdout, stderr io.Writer) int {
	fs, opts := meDrawingGetFlags()
	fs.SetOutput(stderr)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if opts.Name == "" {
		fmt.Fprintln(stderr, "dcs-sms me drawing get: --name is required")
		return 2
	}
	luaArgs := fmt.Sprintf("{ name = %s }", luaQuote(opts.Name))

	resp, exitCode := runMeVerb("drawing_get", luaArgs, opts.Timeout, opts.SavedGames, stderr)
	if exitCode != 0 {
		return exitCode
	}
	return emitMeResponse(resp, opts.Pretty, stdout)
}
