package genunits

import (
	"fmt"
	"io"
	"sort"
	"strings"
)

// ClassifiedEntry is an Entry that has gone through Classify + Sanitize +
// origin lookup. It is the input to the emitter.
type ClassifiedEntry struct {
	Bucket      Bucket
	Type        string // verbatim DCS type-string (right-hand side of assignment)
	Identifier  string // sanitized Lua identifier (left-hand side of assignment)
	OriginLabel string // friendly origin label or "" for base-game
}

// EmitUnits writes the framework/units.lua source for the given classified
// entries (those with Bucket.Top == "units") to w.
func EmitUnits(w io.Writer, entries []ClassifiedEntry, datamineCommit, generatedAt string) error {
	return emit(w, entries, "units",
		"sms.constants.units", "sms.GroupSpawnType",
		datamineCommit, generatedAt)
}

// EmitStatics writes framework/statics.lua source for the given classified
// entries (those with Bucket.Top == "statics") to w.
func EmitStatics(w io.Writer, entries []ClassifiedEntry, datamineCommit, generatedAt string) error {
	return emit(w, entries, "statics",
		"sms.constants.statics", "sms.StaticSpawnType",
		datamineCommit, generatedAt)
}

func emit(w io.Writer, entries []ClassifiedEntry, top, ns, alias, commit, ts string) error {
	// Filter to the requested top-level namespace.
	var mine []ClassifiedEntry
	for _, e := range entries {
		if e.Bucket.Top == top {
			mine = append(mine, e)
		}
	}

	// Sort by identifier for deterministic output. Within a bucket, the
	// loop below relies on sorted-by-bucket-then-identifier order.
	sort.Slice(mine, func(i, j int) bool {
		ai, aj := mine[i].Bucket, mine[j].Bucket
		if ai.Cat != aj.Cat {
			return ai.Cat < aj.Cat
		}
		if ai.Sub != aj.Sub {
			return ai.Sub < aj.Sub
		}
		return mine[i].Identifier < mine[j].Identifier
	})

	// Header
	fmt.Fprintln(w, "-- AUTO-GENERATED by `dcs-sms gen-units`. Do not edit by hand.")
	if commit != "" {
		fmt.Fprintf(w, "-- Source: dcs-lua-datamine @ %s  (regenerated %s)\n", commit, ts)
	} else {
		fmt.Fprintf(w, "-- Source: dcs-lua-datamine (regenerated %s)\n", ts)
	}
	fmt.Fprintf(w, "-- See docs/api/%s.md for usage.\n", top)
	fmt.Fprintln(w)
	fmt.Fprintln(w, `assert(type(sms) == "table", "framework/sms.lua must be loaded first")`)
	fmt.Fprintf(w, "local log = sms.log.module(%q)\n", ns)
	fmt.Fprintln(w)

	// LuaCATS alias — every type-string, alphabetical.
	types := make([]string, 0, len(mine))
	seenType := map[string]bool{}
	for _, e := range mine {
		if !seenType[e.Type] {
			types = append(types, e.Type)
			seenType[e.Type] = true
		}
	}
	sort.Strings(types)
	fmt.Fprintf(w, "---@alias %s\n", alias)
	for _, ty := range types {
		fmt.Fprintf(w, "---| %q\n", ty)
	}
	fmt.Fprintln(w)

	// Namespace declaration
	fmt.Fprintf(w, "---@class %s\n", ns)
	fmt.Fprintf(w, "%s = %s or {}\n", ns, ns)
	fmt.Fprintln(w)

	// Tables, grouped by Cat then Sub.
	type group struct {
		cat, sub string
		entries  []ClassifiedEntry
	}
	groups := []group{}
	for _, e := range mine {
		if len(groups) == 0 || groups[len(groups)-1].cat != e.Bucket.Cat || groups[len(groups)-1].sub != e.Bucket.Sub {
			groups = append(groups, group{cat: e.Bucket.Cat, sub: e.Bucket.Sub})
		}
		groups[len(groups)-1].entries = append(groups[len(groups)-1].entries, e)
	}

	// Emit one outer table per Cat. Sub-buckets are nested within.
	prevCat := ""
	openCat := false
	for i, g := range groups {
		if g.cat != prevCat {
			if openCat {
				fmt.Fprintln(w, "}")
				fmt.Fprintln(w)
			}
			fmt.Fprintf(w, "%s.%s = {\n", ns, g.cat)
			prevCat = g.cat
			openCat = true
		}
		// Sub-bucket header (only if this group has a sub)
		indent := "  "
		if g.sub != "" {
			fmt.Fprintf(w, "%s%s = {\n", indent, g.sub)
			indent = "    "
		}
		for _, e := range g.entries {
			line := fmt.Sprintf("%s%s = %q,", indent, e.Identifier, e.Type)
			if e.OriginLabel != "" {
				line = padToColumn(line, 60) + " -- " + e.OriginLabel
			}
			fmt.Fprintln(w, line)
		}
		if g.sub != "" {
			fmt.Fprintln(w, "  },")
		}
		// Look ahead: close the cat-table if next group is a different cat or this is the last group
		isLast := i == len(groups)-1
		if isLast || groups[i+1].cat != g.cat {
			fmt.Fprintln(w, "}")
			fmt.Fprintln(w)
			openCat = false
			prevCat = ""
		}
	}

	// origin_of helper
	fmt.Fprintln(w, "-- ============================================================")
	fmt.Fprintln(w, "-- Origin lookup")
	fmt.Fprintln(w, "-- ============================================================")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "local _origin = {")
	originOrdered := append([]ClassifiedEntry(nil), mine...)
	sort.Slice(originOrdered, func(i, j int) bool { return originOrdered[i].Type < originOrdered[j].Type })
	for _, e := range originOrdered {
		if e.OriginLabel == "" {
			continue
		}
		fmt.Fprintf(w, "  [%q] = %q,\n", e.Type, e.OriginLabel)
	}
	fmt.Fprintln(w, "}")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "---@param type_string string  DCS type-string to look up")
	fmt.Fprintln(w, "---@return string|nil  asset-pack label if non-base, nil otherwise")
	fmt.Fprintf(w, "%s.origin_of = function(type_string)\n", ns)
	fmt.Fprintln(w, "  if type(type_string) ~= \"string\" then return nil end")
	fmt.Fprintln(w, "  return _origin[type_string]")
	fmt.Fprintln(w, "end")

	return nil
}

// padToColumn returns s padded with spaces to at least width columns.
func padToColumn(s string, width int) string {
	if len(s) >= width {
		return s
	}
	return s + strings.Repeat(" ", width-len(s))
}
